<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="RazorLight" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\PracticalWork.Library.MessageBroker\PracticalWork.Library.MessageBroker.csproj" />
    <ProjectReference Include="..\..\PracticalWork.Library.SharedKernel\PracticalWork.Library.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="resources\ReturnReminder.cshtml" />
    <EmbeddedResource Include="resources\WeeklyReport.cshtml" />
  </ItemGroup>
</Project>
